# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
 languageCode: zh-cn
 # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
 contentDir: content/zh
 weight: 1
 title: 清华大学先进计算技术与系统实验室
 menus:
    main:
      - name: 首页
        url: ""
        weight: 10

      - name: 研究领域
        url: field/
        weight: 20

      - name: 项目工程
        url: project/
        weight: 20

      - name: 最新成果
        url: post/
        weight: 40

      - name: 成员情况
        url: people/
        weight: 50

      - name: 论文发表
        url: publication/
        weight: 60

      - name: 联系我们
        url: contact/
        weight: 70


# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  weight: 2
  title: THU-ACTS
  menus:
    main:
      - name: Home
        url: ""
        weight: 10

      - name: Themes
        url: field/
        weight: 20

      - name: Project
        url: project/
        weight: 20   

      - name: News
        url: post/
        weight: 40

      - name: People
        url: people/
        weight: 50

      - name: Publications
        url: publication/
        weight: 60

      - name: Contact
        url: contact/
        weight: 70





#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
